---
- name: "Create influxdata repository"
  ansible.builtin.yum_repository:
    name: "influxdata"
    description: "InfluxData Repository - Stable"
    baseurl: "https://repos.influxdata.com/stable/x86_64/main"
    gpgkey: "https://repos.influxdata.com/influxdata-archive_compat.key"
    gpgcheck: true
    enabled: true
    file: "influxdata"
    state: present

- name: "Install telegraf"
  ansible.builtin.yum:
    name: telegraf
    state: present

- name: "Copy /etc/telegraf/telegraf.conf"
  ansible.builtin.template:
    src: etc/telegraf/telegraf.conf.j2
    dest: /etc/telegraf/telegraf.conf
    mode: "0640"
    owner: root
    group: telegraf
  notify: "Restart telegraf"

- name: "Start telegraf service"
  ansible.builtin.systemd:
    name: telegraf
    state: restarted
