---
- name: "Gather facts"
  ansible.builtin.setup:
    gather_subset: 'min'
  when: ansible_os_family is not defined

- name: "Load OS-specific variables"
  include_vars: "{{ ansible_os_family }}.yml"

- name: "Install telegraf"
  include_tasks: "{{ ansible_os_family }}.yml"

- name: "Copy /etc/telegraf/telegraf.conf"
  ansible.builtin.template:
    src: etc/telegraf/telegraf.conf.j2
    dest: /etc/telegraf/telegraf.conf
    mode: "0640"
    owner: "{{ telegraf_user }}"
    group: "{{ telegraf_group }}"
  notify: "Restart telegraf"

- name: "Start telegraf service"
  ansible.builtin.systemd:
    name: telegraf
    state: restarted
